//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIlitaryOfficeAshSka.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilitaryTicket()
        {
            this.Militarian = new HashSet<Militarian>();
        }
    
        public int IDMilitaryTicket { get; set; }
        public bool CriminalRecord { get; set; }
        public int IDShelfLifeCategory { get; set; }
        public int IDTypeOfService { get; set; }
        public string DiscriptionTicket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Militarian> Militarian { get; set; }
        public virtual ShelfLifeCategory ShelfLifeCategory { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
    }
}
