//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIlitaryOfficeAshSka.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Militarian
    {
        public int IDMilitarian { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public int IDPassport { get; set; }
        public string FactAddress { get; set; }
        public bool AvailabilityOfAssigned { get; set; }
        public bool AvailabilityOfMilitaryTicket { get; set; }
        public string DiscriptionIll { get; set; }
        public int IDDriverLicence { get; set; }
        public int IDStatus { get; set; }
        public int IDRank { get; set; }
        public int IDPlace { get; set; }
        public int IDPost { get; set; }
        public string Photo { get; set; }
        public int IDMilitaryTicket { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SportsСategory { get; set; }
        public string CivilSpecialty { get; set; }
        public string Education { get; set; }
        public int IDMaritalStatus { get; set; }
    
        public virtual DriverLicence DriverLicence { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        public virtual MilitaryTicket MilitaryTicket { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Place Place { get; set; }
        public virtual Post Post { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Status Status { get; set; }
    }
}
